"""FastAPI application — REST API + WebSocket + visual panel.

Serves:
  * ``/api/v1/*``        — REST endpoints for the library
  * ``/ws/activity``     — WebSocket broadcasting activity log entries
  * ``/``                — Visual panel (static HTML/CSS/JS)
  * ``/demo``            — Demo page
  * ``/docs``            — OpenAPI docs (auto-generated by FastAPI)
"""

from __future__ import annotations

import asyncio
import json
import logging
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from src.app import AppContext, create_app, shutdown_app
from src.config import get_settings

logger = logging.getLogger(__name__)

class SearchRequest(BaseModel):
    query: str
    max_results: int = Field(default=10, ge=1, le=50)
    primary_category: str = ""
    auto_enrich: bool = False
    summarize: bool = False

class QueryRequest(BaseModel):
    query: str
    top_k: int = Field(default=5, ge=1, le=50)
    min_citations: int = Field(default=0, ge=0)
    venue: str = ""
    primary_category: str = ""
    rerank: bool = True

class SummaryRequest(BaseModel):
    sections: list[str] | None = None
    force: bool = False

class IdeaRequest(BaseModel):
    num_ideas: int = Field(default=3, ge=1, le=5)
    focus_area: str = "methodological"

class IdeaStatusRequest(BaseModel):
    status: str = Field(pattern="^(pending|approved|rejected)$")

class NoveltyRequest(BaseModel):
    search_query: str = ""

_ctx: AppContext | None = None

def get_ctx() -> AppContext:
    if _ctx is None:
        raise RuntimeError("App context not initialised")
    return _ctx

class ActivityBroadcaster:
    """Manages WebSocket connections and broadcasts activity updates."""

    def __init__(self) -> None:
        self._connections: list[WebSocket] = []

    async def connect(self, ws: WebSocket) -> None:
        await ws.accept()
        self._connections.append(ws)

    def disconnect(self, ws: WebSocket) -> None:
        if ws in self._connections:
            self._connections.remove(ws)

    async def broadcast(self, message: dict) -> None:
        dead: list[WebSocket] = []
        for ws in self._connections:
            try:
                await ws.send_json(message)
            except Exception:
                dead.append(ws)
        for ws in dead:
            self.disconnect(ws)

broadcaster = ActivityBroadcaster()

async def _activity_poller() -> None:
    """Background task that polls the activity log and broadcasts new entries."""
    ctx = get_ctx()
    last_id = 0
    while True:
        try:
            rows = ctx.db.list_activity(limit=10)
            new_rows = [r for r in rows if r.id and r.id > last_id]
            for r in new_rows:
                if r.id:
                    last_id = max(last_id, r.id)
                await broadcaster.broadcast({
                    "id": r.id,
                    "action_type": r.action_type,
                    "arxiv_id": r.arxiv_id,
                    "query": r.query,
                    "status": r.status,
                    "created_at": r.created_at,
                })
        except Exception:
            logger.debug("Activity poller error", exc_info=True)
        await asyncio.sleep(2.0)

@asynccontextmanager
async def lifespan(app: FastAPI):
    global _ctx
    settings = get_settings()
    settings.ensure_dirs()
    _ctx = create_app()
    poller = asyncio.create_task(_activity_poller())
    logger.info("FastAPI started — visual panel at http://%s:%d",
                settings.host, settings.port)
    try:
        yield
    finally:
        poller.cancel()
        try:
            await poller
        except asyncio.CancelledError:
            pass
        shutdown_app(_ctx)
        _ctx = None

app = FastAPI(
    title="Research Library MCP",
    description="Local-first arXiv research library for coding agents.",
    version="0.1.0",
    lifespan=lifespan,
)

@app.get("/api/v1/health")
async def health() -> dict:
    """Liveness check + model readiness."""
    ctx = get_ctx()
    return {
        "status": "ok",
        "papers": ctx.db.count_papers(),
        "chroma_chunks": ctx.chroma.count(),
        "model_state": ctx.models.model_state,
    }

@app.get("/api/v1/library")
async def list_library(
    limit: int = 20,
    offset: int = 0,
    sort_by: str = "created_at",
    primary_category: str = "",
    min_citations: int = 0,
    venue: str = "",
) -> dict:
    """List papers in the library with filters and pagination."""
    ctx = get_ctx()
    return ctx.library.list_library(
        limit=limit, offset=offset, sort_by=sort_by,
        primary_category=primary_category or None,
        min_citations=min_citations or None,
        venue=venue or None,
    )

@app.get("/api/v1/library/{arxiv_id}")
async def get_paper(arxiv_id: str) -> JSONResponse:
    """Get full metadata, metrics, summaries, and ideas for a paper."""
    ctx = get_ctx()
    detail = ctx.library.get_paper_detail(arxiv_id)
    if not detail:
        return JSONResponse(
            status_code=404,
            content={"error": "not_found", "message": f"Paper {arxiv_id} not in library."},
        )
    return detail

@app.post("/api/v1/library/search")
async def search_papers(req: SearchRequest) -> dict:
    """Search arXiv and import results.  Runs in a thread to avoid blocking."""
    ctx = get_ctx()
    results = await asyncio.to_thread(
        ctx.library.search_and_import,
        query=req.query,
        max_results=req.max_results,
        primary_category=req.primary_category or None,
        auto_enrich=req.auto_enrich,
    )
    out = {
        "papers": [r.to_dict() for r in results],
        "total_found": len(results),
    }
    if req.summarize and results:
        for r in results[:5]:
            try:
                await asyncio.to_thread(ctx.summarizer.summarize, r.arxiv_id)
            except Exception as exc:
                logger.warning("Summary failed for %s: %s", r.arxiv_id, exc)
    return out

@app.post("/api/v1/library/query")
async def query_library(req: QueryRequest) -> dict:
    """Vector + metadata search over the local library."""
    ctx = get_ctx()
    results = await asyncio.to_thread(
        ctx.library.query_library,
        query=req.query,
        top_k=req.top_k,
        min_citations=req.min_citations or None,
        venue=req.venue or None,
        primary_category=req.primary_category or None,
        rerank=req.rerank,
    )
    return {"results": [r.to_dict() for r in results]}

@app.delete("/api/v1/library/{arxiv_id}")
async def remove_paper(arxiv_id: str) -> dict:
    """Remove a paper and all derived data from the library."""
    ctx = get_ctx()
    removed = await asyncio.to_thread(ctx.library.remove_paper, arxiv_id)
    return {"removed": removed, "arxiv_id": arxiv_id}

@app.post("/api/v1/summaries/{arxiv_id}")
async def generate_summary(arxiv_id: str, req: SummaryRequest) -> JSONResponse:
    """Generate or retrieve a structured summary for a paper."""
    ctx = get_ctx()
    try:
        result = await asyncio.to_thread(
            ctx.summarizer.summarize,
            arxiv_id,
            req.sections,
            req.force,
        )
        return {"arxiv_id": arxiv_id, "summaries": result}
    except ValueError as exc:
        return JSONResponse(
            status_code=404,
            content={"error": "not_found", "message": str(exc)},
        )

@app.get("/api/v1/summaries/{arxiv_id}")
async def get_summaries(arxiv_id: str) -> dict:
    """Get all cached summaries for a paper (no LLM call)."""
    ctx = get_ctx()
    return {"arxiv_id": arxiv_id, "summaries": ctx.summarizer.get_cached(arxiv_id)}

@app.post("/api/v1/ideas/{arxiv_id}")
async def generate_ideas(arxiv_id: str, req: IdeaRequest) -> JSONResponse:
    """Generate novel research ideas for a paper."""
    ctx = get_ctx()
    try:
        result = await asyncio.to_thread(
            ctx.ideas.generate_ideas,
            arxiv_id,
            req.num_ideas,
            req.focus_area,
        )
        return {"arxiv_id": arxiv_id, "ideas": result}
    except ValueError as exc:
        return JSONResponse(
            status_code=404,
            content={"error": "not_found", "message": str(exc)},
        )

@app.get("/api/v1/ideas/{arxiv_id}")
async def list_ideas(arxiv_id: str) -> dict:
    """List all ideas for a paper."""
    ctx = get_ctx()
    return {"arxiv_id": arxiv_id, "ideas": ctx.ideas.list_ideas(arxiv_id)}

@app.post("/api/v1/ideas/{idea_id}/status")
async def update_idea_status(idea_id: int, req: IdeaStatusRequest) -> JSONResponse:
    """Approve or reject an idea (human-in-the-loop)."""
    ctx = get_ctx()
    ok = ctx.ideas.update_status(idea_id, req.status)
    if not ok:
        return JSONResponse(
            status_code=404,
            content={"error": "not_found", "message": f"Idea {idea_id} not found."},
        )
    return {"idea_id": idea_id, "status": req.status}

@app.post("/api/v1/novelty/{idea_id}")
async def verify_novelty(idea_id: int, req: NoveltyRequest) -> JSONResponse:
    """Run novelty re-verification on an idea."""
    ctx = get_ctx()
    try:
        result = await asyncio.to_thread(
            ctx.novelty.verify_novelty,
            idea_id,
            req.search_query or None,
        )
        return result
    except ValueError as exc:
        return JSONResponse(
            status_code=404,
            content={"error": "not_found", "message": str(exc)},
        )

@app.get("/api/v1/activity")
async def get_activity(limit: int = 50, action_type: str = "") -> dict:
    """Return recent agent actions from the activity log."""
    ctx = get_ctx()
    rows = ctx.db.list_activity(limit=limit, action_type=action_type or None)
    return {
        "activities": [
            {
                "id": r.id,
                "action_type": r.action_type,
                "arxiv_id": r.arxiv_id,
                "query": r.query,
                "status": r.status,
                "metadata": r.metadata_json,
                "created_at": r.created_at,
            }
            for r in rows
        ]
    }

@app.websocket("/ws/activity")
async def ws_activity(ws: WebSocket) -> None:
    """WebSocket endpoint that streams activity log updates in real-time."""
    await broadcaster.connect(ws)
    try:
        while True:
            await ws.receive_text()
    except WebSocketDisconnect:
        broadcaster.disconnect(ws)

_FRONTEND_DIR = Path(__file__).resolve().parent / "frontend"

@app.get("/paper/{arxiv_id}")
async def serve_paper_page(arxiv_id: str) -> FileResponse:
    """Serve the paper detail HTML page for any /paper/{arxiv_id} path."""
    page = _FRONTEND_DIR / "paper.html"
    if page.exists():
        return FileResponse(str(page), media_type="text/html")
    return JSONResponse(status_code=404, content={"error": "not_found"})

@app.get("/activity")
async def serve_activity_page() -> FileResponse:
    """Serve the activity log HTML page."""
    page = _FRONTEND_DIR / "activity.html"
    if page.exists():
        return FileResponse(str(page), media_type="text/html")
    return JSONResponse(status_code=404, content={"error": "not_found"})

@app.post("/api/v1/library/{arxiv_id}/enrich")
async def enrich_paper(arxiv_id: str) -> JSONResponse:
    """Enrich a paper with Semantic Scholar citation/venue metrics."""
    ctx = get_ctx()
    paper = ctx.db.get_paper(arxiv_id)
    if not paper:
        return JSONResponse(
            status_code=404,
            content={"error": "not_found", "message": f"Paper {arxiv_id} not in library."},
        )
    try:
        metrics = await asyncio.to_thread(ctx.library.enrich_paper_sync, arxiv_id)
        return {
            "arxiv_id": arxiv_id,
            "citation_count": metrics.citation_count,
            "influential_citation_count": metrics.influential_citation_count,
            "venue": metrics.venue,
        }
    except Exception as exc:
        logger.warning("Enrichment failed for %s: %s", arxiv_id, exc)
        return JSONResponse(
            status_code=502,
            content={"error": "enrich_failed", "message": str(exc)},
        )

if _FRONTEND_DIR.exists():
    _demo_dir = _FRONTEND_DIR / "demo"
    if _demo_dir.exists():
        app.mount("/demo", StaticFiles(directory=str(_demo_dir), html=True),
                  name="demo")
    app.mount("/", StaticFiles(directory=str(_FRONTEND_DIR), html=True),
              name="frontend")

def main() -> int:
    """Entry point for the FastAPI server."""
    import uvicorn

    settings = get_settings()
    uvicorn.run(
        "src.api.main:app",
        host=settings.host,
        port=settings.port,
        reload=False,
    )
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
